// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2lhRT2xR0Vb8BjO2nuAwdn90HkXUM3g',
    appId: '1:955687000882:web:d58a432f1a27241578952b',
    messagingSenderId: '955687000882',
    projectId: 'brtodo',
    authDomain: 'brtodo.firebaseapp.com',
    storageBucket: 'brtodo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8E4jEwu819RvGytH9miI1VySXxGv4mLM',
    appId: '1:955687000882:android:0f576f9e572242e278952b',
    messagingSenderId: '955687000882',
    projectId: 'brtodo',
    storageBucket: 'brtodo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDghBD1h7lYI4M2vlzuKN0SPVHQw6FwJuA',
    appId: '1:955687000882:ios:f75c7f3b33e59a2d78952b',
    messagingSenderId: '955687000882',
    projectId: 'brtodo',
    storageBucket: 'brtodo.firebasestorage.app',
    iosBundleId: 'com.example.brTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDghBD1h7lYI4M2vlzuKN0SPVHQw6FwJuA',
    appId: '1:955687000882:ios:f75c7f3b33e59a2d78952b',
    messagingSenderId: '955687000882',
    projectId: 'brtodo',
    storageBucket: 'brtodo.firebasestorage.app',
    iosBundleId: 'com.example.brTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2lhRT2xR0Vb8BjO2nuAwdn90HkXUM3g',
    appId: '1:955687000882:web:bbab259b4a8fef3a78952b',
    messagingSenderId: '955687000882',
    projectId: 'brtodo',
    authDomain: 'brtodo.firebaseapp.com',
    storageBucket: 'brtodo.firebasestorage.app',
  );
}
